### ISSUE TITLE
Step 7. WeaponItem moves slightly upwards when dropped

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#61] opened 2019-03-11 20:34 UTC
Happened once so far on the final hardware (in Chrome), then was magically resolved when switching back to finger input after trying with mouse input (issue persisted during trial with mouse input).

**Comment by bertez** [comment] 2019-03-11 20:55
Yes, this is by design. The weapon items when dropped will always move slightly because the size is not the same when is dragged, and cannot be dragged with the real size because there are a lot of different sizes and the size change effect is less usable on the start drag event than the end one...

**Comment by phivk** [comment] 2019-03-11 21:24
No, this was a temporary issue and not 'normal behaviour' as you suggest. Not sure why it was resolved, but seems to be resolved after using mouse for drag and drop.

This occurred for WeaponItems that were already present on the canvas (not dropping WeaponItems from the SideBar).

see video demonstration: https://photos.app.goo.gl/XweypYYmrNWqWjnV6

**Comment by bertez** [comment] 2019-03-18 10:42
Should be fixed on:
https://github.com/unfoldcollective/Insurgent-of-Myjava/commit/202e15df48c36cd713bc7de4037fda337cefc79f

**Closed by bertez** 2019-03-18 10:42 UTC
Labels: bug
